apiVersion: v1
kind: Service
metadata:
    name: svc-deployment-games
    namespace: games
spec:
    type: ClusterIP
    ports:
        - port: 80 # Porta padr√£o da service
          targetPort: 8080 # Porta alvo do Pod
    selector:
        app: pod-games